version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        S3_BUCKET1: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 16
    commands:
        - echo Installing source NPM dependencies...
        - cd my-app
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build  
        - echo build process finished, we should uplload to S3 now
        - aws s3 sync dist s3://www.validitii.com 
        - aws s3 sync dist s3://validitii.com 
artifacts:
    files:
        - '**/*'
    base-directory: '**/dist'
    discard-paths: yes